
package com.dbdky.csls.I2ServiceC;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "I2ServiceImplService", targetNamespace = "http://csls.dbdky.com/", wsdlLocation = "http://localhost:8888/I2Service?wsdl")
public class I2ServiceImplService
    extends Service
{

    private final static URL I2SERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException I2SERVICEIMPLSERVICE_EXCEPTION;
    private final static QName I2SERVICEIMPLSERVICE_QNAME = new QName("http://csls.dbdky.com/", "I2ServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/I2Service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        I2SERVICEIMPLSERVICE_WSDL_LOCATION = url;
        I2SERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public I2ServiceImplService() {
        super(__getWsdlLocation(), I2SERVICEIMPLSERVICE_QNAME);
    }

    public I2ServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), I2SERVICEIMPLSERVICE_QNAME, features);
    }

    public I2ServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, I2SERVICEIMPLSERVICE_QNAME);
    }

    public I2ServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, I2SERVICEIMPLSERVICE_QNAME, features);
    }

    public I2ServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public I2ServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns I2Service
     */
    @WebEndpoint(name = "I2ServiceImplPort")
    public I2Service getI2ServiceImplPort() {
        return super.getPort(new QName("http://csls.dbdky.com/", "I2ServiceImplPort"), I2Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns I2Service
     */
    @WebEndpoint(name = "I2ServiceImplPort")
    public I2Service getI2ServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://csls.dbdky.com/", "I2ServiceImplPort"), I2Service.class, features);
    }

    private static URL __getWsdlLocation() {
        if (I2SERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw I2SERVICEIMPLSERVICE_EXCEPTION;
        }
        return I2SERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
