
package com.dbdky.csls.I2ServiceC;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "I2Service", targetNamespace = "http://csls.dbdky.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface I2Service {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://csls.dbdky.com/I2Service/uploadCACHeartbeatInfoRequest", output = "http://csls.dbdky.com/I2Service/uploadCACHeartbeatInfoResponse")
    public String uploadCACHeartbeatInfo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://csls.dbdky.com/I2Service/uploadCACDataRequest", output = "http://csls.dbdky.com/I2Service/uploadCACDataResponse")
    public String uploadCACData(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://csls.dbdky.com/I2Service/uploadCACConfigRequest", output = "http://csls.dbdky.com/I2Service/uploadCACConfigResponse")
    public String uploadCACConfig(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://csls.dbdky.com/I2Service/downloadCAGCtrlRequest", output = "http://csls.dbdky.com/I2Service/downloadCAGCtrlResponse")
    public String downloadCAGCtrl(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://csls.dbdky.com/I2Service/downloadCACLatestVersionRequest", output = "http://csls.dbdky.com/I2Service/downloadCACLatestVersionResponse")
    public String downloadCACLatestVersion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://csls.dbdky.com/I2Service/downloadCACHistoryVersionRequest", output = "http://csls.dbdky.com/I2Service/downloadCACHistoryVersionResponse")
    public String downloadCACHistoryVersion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://csls.dbdky.com/I2Service/downloadCACUpdateFileRequest", output = "http://csls.dbdky.com/I2Service/downloadCACUpdateFileResponse")
    public String downloadCACUpdateFile(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
