// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxymsg.proto

package com.dbdky.csls.methodutil;

public final class ProxyMsgProto {
  private ProxyMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProxyMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .dbdky.ProxyMsg.MSGTYPE msgtype = 1 [default = HEARTBEATINFO];
    /**
     * <code>required .dbdky.ProxyMsg.MSGTYPE msgtype = 1 [default = HEARTBEATINFO];</code>
     */
    boolean hasMsgtype();
    /**
     * <code>required .dbdky.ProxyMsg.MSGTYPE msgtype = 1 [default = HEARTBEATINFO];</code>
     */
    com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.MSGTYPE getMsgtype();

    // required string msgbody = 2;
    /**
     * <code>required string msgbody = 2;</code>
     */
    boolean hasMsgbody();
    /**
     * <code>required string msgbody = 2;</code>
     */
    java.lang.String getMsgbody();
    /**
     * <code>required string msgbody = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgbodyBytes();
  }
  /**
   * Protobuf type {@code dbdky.ProxyMsg}
   */
  public static final class ProxyMsg extends
      com.google.protobuf.GeneratedMessage
      implements ProxyMsgOrBuilder {
    // Use ProxyMsg.newBuilder() to construct.
    private ProxyMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProxyMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProxyMsg defaultInstance;
    public static ProxyMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ProxyMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProxyMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.MSGTYPE value = com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.MSGTYPE.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgtype_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msgbody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dbdky.csls.methodutil.ProxyMsgProto.internal_static_dbdky_ProxyMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dbdky.csls.methodutil.ProxyMsgProto.internal_static_dbdky_ProxyMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.class, com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ProxyMsg> PARSER =
        new com.google.protobuf.AbstractParser<ProxyMsg>() {
      public ProxyMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProxyMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProxyMsg> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code dbdky.ProxyMsg.MSGTYPE}
     */
    public enum MSGTYPE
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HEARTBEATINFO = 0;</code>
       */
      HEARTBEATINFO(0, 0),
      /**
       * <code>MONITORDATA = 1;</code>
       */
      MONITORDATA(1, 1),
      ;

      /**
       * <code>HEARTBEATINFO = 0;</code>
       */
      public static final int HEARTBEATINFO_VALUE = 0;
      /**
       * <code>MONITORDATA = 1;</code>
       */
      public static final int MONITORDATA_VALUE = 1;


      public final int getNumber() { return value; }

      public static MSGTYPE valueOf(int value) {
        switch (value) {
          case 0: return HEARTBEATINFO;
          case 1: return MONITORDATA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MSGTYPE>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MSGTYPE>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MSGTYPE>() {
              public MSGTYPE findValueByNumber(int number) {
                return MSGTYPE.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MSGTYPE[] VALUES = values();

      public static MSGTYPE valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MSGTYPE(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:dbdky.ProxyMsg.MSGTYPE)
    }

    private int bitField0_;
    // required .dbdky.ProxyMsg.MSGTYPE msgtype = 1 [default = HEARTBEATINFO];
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.MSGTYPE msgtype_;
    /**
     * <code>required .dbdky.ProxyMsg.MSGTYPE msgtype = 1 [default = HEARTBEATINFO];</code>
     */
    public boolean hasMsgtype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .dbdky.ProxyMsg.MSGTYPE msgtype = 1 [default = HEARTBEATINFO];</code>
     */
    public com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.MSGTYPE getMsgtype() {
      return msgtype_;
    }

    // required string msgbody = 2;
    public static final int MSGBODY_FIELD_NUMBER = 2;
    private java.lang.Object msgbody_;
    /**
     * <code>required string msgbody = 2;</code>
     */
    public boolean hasMsgbody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string msgbody = 2;</code>
     */
    public java.lang.String getMsgbody() {
      java.lang.Object ref = msgbody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgbody_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgbody = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgbodyBytes() {
      java.lang.Object ref = msgbody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgbody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgtype_ = com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.MSGTYPE.HEARTBEATINFO;
      msgbody_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgbody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgtype_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgbodyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgtype_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgbodyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dbdky.ProxyMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dbdky.csls.methodutil.ProxyMsgProto.internal_static_dbdky_ProxyMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dbdky.csls.methodutil.ProxyMsgProto.internal_static_dbdky_ProxyMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.class, com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.Builder.class);
      }

      // Construct using com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgtype_ = com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.MSGTYPE.HEARTBEATINFO;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgbody_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dbdky.csls.methodutil.ProxyMsgProto.internal_static_dbdky_ProxyMsg_descriptor;
      }

      public com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg getDefaultInstanceForType() {
        return com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.getDefaultInstance();
      }

      public com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg build() {
        com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg buildPartial() {
        com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg result = new com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgtype_ = msgtype_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgbody_ = msgbody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg) {
          return mergeFrom((com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg other) {
        if (other == com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.getDefaultInstance()) return this;
        if (other.hasMsgtype()) {
          setMsgtype(other.getMsgtype());
        }
        if (other.hasMsgbody()) {
          bitField0_ |= 0x00000002;
          msgbody_ = other.msgbody_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgtype()) {
          
          return false;
        }
        if (!hasMsgbody()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .dbdky.ProxyMsg.MSGTYPE msgtype = 1 [default = HEARTBEATINFO];
      private com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.MSGTYPE msgtype_ = com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.MSGTYPE.HEARTBEATINFO;
      /**
       * <code>required .dbdky.ProxyMsg.MSGTYPE msgtype = 1 [default = HEARTBEATINFO];</code>
       */
      public boolean hasMsgtype() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .dbdky.ProxyMsg.MSGTYPE msgtype = 1 [default = HEARTBEATINFO];</code>
       */
      public com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.MSGTYPE getMsgtype() {
        return msgtype_;
      }
      /**
       * <code>required .dbdky.ProxyMsg.MSGTYPE msgtype = 1 [default = HEARTBEATINFO];</code>
       */
      public Builder setMsgtype(com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.MSGTYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .dbdky.ProxyMsg.MSGTYPE msgtype = 1 [default = HEARTBEATINFO];</code>
       */
      public Builder clearMsgtype() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgtype_ = com.dbdky.csls.methodutil.ProxyMsgProto.ProxyMsg.MSGTYPE.HEARTBEATINFO;
        onChanged();
        return this;
      }

      // required string msgbody = 2;
      private java.lang.Object msgbody_ = "";
      /**
       * <code>required string msgbody = 2;</code>
       */
      public boolean hasMsgbody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public java.lang.String getMsgbody() {
        java.lang.Object ref = msgbody_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgbody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgbodyBytes() {
        java.lang.Object ref = msgbody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgbody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public Builder setMsgbody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgbody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public Builder clearMsgbody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgbody_ = getDefaultInstance().getMsgbody();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public Builder setMsgbodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgbody_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dbdky.ProxyMsg)
    }

    static {
      defaultInstance = new ProxyMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dbdky.ProxyMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dbdky_ProxyMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dbdky_ProxyMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016proxymsg.proto\022\005dbdky\"\203\001\n\010ProxyMsg\0227\n\007" +
      "msgtype\030\001 \002(\0162\027.dbdky.ProxyMsg.MSGTYPE:\r" +
      "HEARTBEATINFO\022\017\n\007msgbody\030\002 \002(\t\"-\n\007MSGTYP" +
      "E\022\021\n\rHEARTBEATINFO\020\000\022\017\n\013MONITORDATA\020\001B*\n" +
      "\031com.dbdky.csls.methodutilB\rProxyMsgProt" +
      "o"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_dbdky_ProxyMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_dbdky_ProxyMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dbdky_ProxyMsg_descriptor,
              new java.lang.String[] { "Msgtype", "Msgbody", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
